# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
    # Resource Group
  - name: rgname
    type: string
    default: tfstate-rg
    # 스토리지 어카운트 이름
  - name: stgaccount
    type: string
    default: 'ezcustomertfstate01'
    # 컨테이너 이름
  - name: container
    type: string
    default: 'terraform-states'
    # tfstate 파일 이름
  - name: key
    type: string
    default: 'prod_network.tfstate'
stages:
  - stage: Plan
    displayName: Plan
    jobs:
      - job:
            
  - stage: destroy
    displayName: terraform destroy
    jobs:
      - job: 
        steps:
        
        - task: TerraformTaskV4@4
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/2.prod_networks'
            backendServiceArm: 'MPN Subscription'
            backendAzureRmResourceGroupName: ${{parameters.rgname}}
            backendAzureRmStorageAccountName: ${{parameters.stgaccount}}
            backendAzureRmContainerName: ${{parameters.container}}
            backendAzureRmKey: ${{parameters.key}}

        - task: TerraformTaskV4@4
          displayName: terraform destroy
          inputs:
            provider: 'azurerm'
            command: 'destroy'
            workingDirectory: '$(System.DefaultWorkingDirectory)/2.prod_networks'
            environmentServiceNameAzureRM: 'MPN Subscription'