apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: mysql-pv-nfs
  storageClassName: ''