apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: wordpress-pv-nfs
  storageClassName: ''